import React from 'react'
import ReactDOM from 'react-dom/client'
// import App from './01-base/class 01'
// import App from './01-base/function02'
// import  App from './01-base/nesting03'
// import  App from './01-base/04css'
// import  App from './01-base/05event'
// import  App from './01-base/06event02'
// import  App from './01-base/07ref'
// import  App from './01-base/08status'
// import App from './01-base/09looprender'
// import App from './01-base/10todolist'
// import App from './01-base/11dangerouslyinnerHtml'
// import App from './01-base/12optioncard'
// import App from './01-base/13setstatedifftime'
// import App from './01-base/14betterScroll'
// import App from './01-base/15betterScrollCinema'
// import App from './01-base/16props'
// import App from './01-base/17functioncomponent'
// import App from './01-base/18statasvsattribute'
// import App from './01-base/19uncontrol'
// import App from './01-base/20contorl'
// import App from './01-base/21controlcinema'
// import App from './01-base/22controltodolist'
// import App from './02-advance/01childtoparent'
// import App from './02-advance/02uncontroloptionalcard'
// import App from './02-advance/03controloptionalcard'
// import App from './02-advance/04communication'
// import App from './02-advance/05ref_form'
// import App from './02-advance/06statusadvance'
// import App from './02-advance/07announcer_subsciber'
// import App from './02-advance/08announcer_subsciber_case'
// import App from './02-advance/09context'
// import App from './02-advance/11slotdrawer'
// import App from './02-advance/12lifecycle'
// import App from './02-advance/13lifecyclecase'
// import App from './02-advance/14lifecycle_runningstage'
// import App from './02-advance/15lifecycle_updatestage'
// import App from './02-advance/16lifecycle_updatestage_case'
// import App from './02-advance/17lifecycle_update3'
// import App from './02-advance/18lifecycle_update3case'
// import App from './02-advance/19lifecycle_destroy'
// import App from './02-advance/20newlifecycle'
// import App from './02-advance/21getDerivedStateFromProps'
// import App from './02-advance/22getSnapshotBeforeUpdate'
// import App from './02-advance/23getSnapshotBeforeUpdateCase'
// import App from './02-advance/24optimization'
// import App from './02-advance/25swiper_Synchronize'
// import App from './02-advance/26swiper_Asynchronous'
// import App from './02-advance/27swiper_component'
// import App from './03-hooks/01useState'
// import App from './03-hooks/02todolist'
// import App from './03-hooks/03useEffect'
// import App from './03-hooks/04useEffect2'
// import App from './03-hooks/05useEffectcase'
// import App from './03-hooks/06useEffect3'
// import App from './03-hooks/07usecallback1'
// import App from './03-hooks/08usecallback2'
// import App from './03-hooks/09useMemo'
// import App from './03-hooks/10useRef'
// import App from './03-hooks/11useRef_savevalue'
// import App from './03-hooks/12useContext'
// import App from './03-hooks/13useReducer'
// import App from './03-hooks/14useReducer2'
// import App from './03-hooks/15useReducer3'
import App from './03-hooks/16customizehooks'

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(
    // <React.StrictMode>
        <App/>
    // </React.StrictMode>
)